# 训练配置
defaults:
  - base.yaml

training:
  epochs: 150
  batch_size: 64
  lr: 0.0004
  optimizer: adam
  scheduler: cosine
  T_max: 10
  eta_min: 0.00001
  loss: # 组合损失
    dice: 0.5 #  dice loss 比例
    cross_entropy: 0.5  # 交叉熵损失比例

outputs:
  log_dir: ./outputs/logs
  ckpt_dir: ./outputs/checkpoints