# 训练配置
defaults:
  - base.yaml

training:
  lr: 0.0004
  optimizer: adam
  scheduler: cosine
  loss: dice
  T_max: 10
  eta_min: 0.00001

outputs:
  log_dir: ./outputs/logs
  ckpt_dir: ./outputs/checkpoints